#!/bin/bash

alias dir='ls -hFx'
alias l='ls -lathF'           
alias L='ls -latrhF'          
alias la='ls -Al'             
alias lc='ls -lcr'            
alias lk='ls -lSr'            
alias lh='ls -lSrh'           
alias lm='ls -al | more'      
alias lo='ls -laSFh'          
alias lr='ls -lR'             
alias lt='ls -ltr'            
alias lu='ls -lur'            
alias l='ls -lah'
alias la='ls -lAh'
alias ll='ls -Fhl --color=auto'
alias lla='ls -Fhla --color=auto'
alias ls='ls -G'
alias lsa='ls -lah'